version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    environment:
      - DJANGO_SETTINGS_MODULE=Avakam.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A Avakam worker --beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  # Сервис для Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
