# Generated by Django 4.2.15 on 2024-08-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('banner', models.ImageField(upload_to='advertisement_banners', verbose_name='Banner photo')),
                ('url', models.URLField(verbose_name='url of site or other link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('duration', models.IntegerField(choices=[(1, '1 days'), (2, '2 days'), (3, '3 days'), (7, '7 days'), (14, '14 days'), (30, '30 days')], verbose_name='duration in days')),
            ],
        ),
    ]
