# Generated by Django 4.2.15 on 2024-12-08 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boosted_at', models.DateTimeField(blank=True, null=True)),
                ('boosts_remaining', models.IntegerField(default=3)),
                ('is_pinned', models.BooleanField(default=False)),
                ('user_have_premium', models.BooleanField(default=False)),
                ('custom_fields', models.JSONField(blank=True, null=True, verbose_name='Дополнительные поля категории')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('image', models.ImageField(upload_to='listing/images', verbose_name='Фото')),
                ('price_type', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('сontract', 'Договорная цена'), ('free', 'Бесплатно')], max_length=30, verbose_name='Тип цены')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='main.category', verbose_name='Категория')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='main.city', verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='main.country', verbose_name='Страна')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_details', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.CreateModel(
            name='ListingDetail',
            fields=[
                ('listing_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='Закреплено в')),
                ('pinned_duration', models.IntegerField(blank=True, null=True, verbose_name='Продолжительность закрепления')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у'), ('not_product', 'Не продукт')], max_length=30, verbose_name='Состояние')),
                ('contact_number', models.CharField(max_length=30, verbose_name='Контактый номер')),
                ('contact_comment', models.CharField(blank=True, max_length=120, null=True, verbose_name='Комментарий')),
                ('listing_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.listing', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Listing Detail',
                'verbose_name_plural': 'Listing Details',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.country', verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('category_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('field_type', models.CharField(choices=[('checkbox', 'Чекбоксы (множественный выбор)'), ('radio', 'Кнопки (один выбор)'), ('range', 'Диапазон (от-до)')], max_length=20, verbose_name='Тип поля')),
                ('options', models.TextField(help_text="Для 'checkbox' и 'radio' варианты через запятую. Для 'range' оставьте пустым.", max_length=250, verbose_name='Варианты')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.category')),
            ],
            options={
                'verbose_name': 'Category field',
                'verbose_name_plural': 'Category fields',
            },
        ),
    ]
